#
# Makefile for linux kernel
#
obj-$(CONFIG_EFI)			+= efi.o vars.o reboot.o capsule.o
obj-$(CONFIG_EFI_VARS)			+= efivars.o
obj-$(CONFIG_EFI_VARS_PSTORE)		+= efi-pstore.o
obj-$(CONFIG_UEFI_CPER)			+= cper.o
obj-$(CONFIG_EFI_CAPSULE_PSTORE)	+= efi-capsule-pstore.o
obj-$(CONFIG_EFI_CAPSULE_BLK_DEV)	+= efi-capsule-blk.o
